laravel/routes/web.php
<?php

use App\Http\Controllers\ACompanhiaController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\CaptacaoDePatrociniosController;
use App\Http\Controllers\CentroDeEstudosController;
use App\Http\Controllers\ContacaoDeHistoriasController;
use App\Http\Controllers\ContatoController;
use App\Http\Controllers\ContratacoesController;
use App\Http\Controllers\CriticasEMateriasController;
use App\Http\Controllers\CursosEOficinasController;
use App\Http\Controllers\DepoimentosController;
use App\Http\Controllers\EspetaculosController;
use App\Http\Controllers\GaleriaDeFotosController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NoticiasController;
use App\Http\Controllers\PoliticaDePrivacidadeController;
use App\Http\Controllers\PremiacoesController;
use App\Http\Controllers\ProjetosEspeciaisController;
use App\Http\Controllers\VideosController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('a-companhia', [ACompanhiaController::class, 'index'])->name('a-companhia');
Route::get('agenda', [AgendaController::class, 'index'])->name('agenda');
Route::get('espetaculos', [EspetaculosController::class, 'index'])->name('espetaculos');
Route::get('espetaculos/{slug}', [EspetaculosController::class, 'show'])->name('espetaculos.show');
Route::get('cursos-e-oficinas', [CursosEOficinasController::class, 'index'])->name('cursos-e-oficinas');
Route::get('cursos-e-oficinas/{slug}', [CursosEOficinasController::class, 'showPlanejamento'])->name('cursos-e-oficinas.planejamento');
Route::get('projetos-especiais', [ProjetosEspeciaisController::class, 'index'])->name('projetos-especiais');
Route::get('centro-de-estudos', [CentroDeEstudosController::class, 'index'])->name('centro-de-estudos');
Route::get('captacao-de-patrocinios', [CaptacaoDePatrociniosController::class, 'index'])->name('captacao-de-patrocinios');
Route::get('contratacoes', [ContratacoesController::class, 'index'])->name('contratacoes');
Route::get('galeria-de-fotos', [GaleriaDeFotosController::class, 'index'])->name('galeria-de-fotos');
Route::get('videos', [VideosController::class, 'index'])->name('videos');
Route::get('noticias', [NoticiasController::class, 'index'])->name('noticias');
Route::get('noticias/{slug}', [NoticiasController::class, 'show'])->name('noticias.show');
Route::get('premiacoes', [PremiacoesController::class, 'index'])->name('premiacoes');
Route::get('criticas-e-materias', [CriticasEMateriasController::class, 'index'])->name('criticas-e-materias');
Route::get('contato', [ContatoController::class, 'index'])->name('contato');
Route::post('contato', [ContatoController::class, 'post'])->name('contato.post');
Route::get('depoimentos', [DepoimentosController::class, 'index'])->name('depoimentos');
Route::post('depoimentos', [DepoimentosController::class, 'post'])->name('depoimentos.post');
Route::get('politica-de-privacidade', [PoliticaDePrivacidadeController::class, 'index'])->name('politica-de-privacidade');
Route::post('aceite-de-cookies', [HomeController::class, 'postCookies'])->name('aceite-de-cookies.post');

require __DIR__.'/auth.php';

laravel/app/Models/Depoimento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Depoimento extends Model
{
    use HasFactory;

    protected $table = 'depoimentos';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function getCreatedAtOrderAttribute()
    {
        return \Carbon\Carbon::createFromFormat('d/m/Y', $this->created_at)->format('Y-m-d');
    }

    public function scopeAprovados($query)
    {
        return $query->where('aprovado', '=', 1);
    }

    public function scopeNaoAprovados($query)
    {
        return $query->where('aprovado', '!=', 1);
    }

    public function scopeEspetaculo($query, $id)
    {
        return $query->where('espetaculo_id', $id);
    }

    public function countNaoAprovados()
    {
        return $this->naoAprovados()->count();
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }
}

laravel/app/Http/Controllers/DepoimentosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DepoimentosRequest;
use App\Models\Contato;
use App\Models\Depoimento;
use App\Notifications\DepoimentosNotification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Notification;

class DepoimentosController extends Controller
{
    public function index()
    {
        $depoimentos = Depoimento::aprovados()
            ->join('espetaculos', 'espetaculos.id', '=', 'depoimentos.espetaculo_id')
            ->select('depoimentos.*', 'espetaculos.slug', 'espetaculos.imagem', 'espetaculos.titulo')
            ->orderBy('created_at', 'desc')->get();

        return view('frontend.depoimentos', compact('depoimentos'));
    }

    public function post(DepoimentosRequest $request, Depoimento $depoimento)
    {
        try {
            $data = $request->all();

            $depoimento->create($data);

            Notification::send(
                Contato::first(),
                new DepoimentosNotification($data)
            );

            return back()->with('enviado', true);
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao enviar depoimento: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;
use Illuminate\Http\Request;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $cookies = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('cookies'));
    }
}

laravel/app/Http/Controllers/Painel/AgendaController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\AgendaRequest;
use App\Models\Agenda;
use App\Models\Espetaculo;
use Illuminate\Http\Request;

class AgendaController extends Controller
{
    public function index()
    {
        $dataAtual = date('Y-m-d');

        $agenda = Agenda::join('espetaculos', 'espetaculos.id', '=', 'agenda.espetaculo_id')
            ->select('agenda.*', 'espetaculos.titulo as espetaculo_titulo', 'espetaculos.imagem as espetaculo_imagem', 'espetaculos.tipo as espetaculo_tipo')
            ->where('data', '>=', $dataAtual)
            ->orderBy('agenda.data', 'desc')->get();

        $anteriores = Agenda::join('espetaculos', 'espetaculos.id', '=', 'agenda.espetaculo_id')
            ->select('agenda.*', 'espetaculos.titulo as espetaculo_titulo', 'espetaculos.imagem as espetaculo_imagem', 'espetaculos.tipo as espetaculo_tipo')
            ->where('data', '<', $dataAtual)
            ->orderBy('agenda.data', 'desc')->get();

        return view('painel.agenda.index', compact('agenda', 'anteriores'));
    }

    public function create()
    {
        $espetaculos = Espetaculo::orderBy('titulo', 'asc')->pluck('titulo', 'id');

        return view('painel.agenda.create', compact('espetaculos'));
    }

    public function store(AgendaRequest $request)
    {
        try {
            $input = $request->all();

            Agenda::create($input);

            return redirect()->route('painel.agenda.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Agenda $agenda)
    {
        $espetaculos = Espetaculo::orderBy('titulo', 'asc')->pluck('titulo', 'id');

        return view('painel.agenda.edit', compact('agenda', 'espetaculos'));
    }

    public function update(AgendaRequest $request, Agenda $agenda)
    {
        try {
            $input = $request->all();

            $agenda->update($input);

            return redirect()->route('painel.agenda.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Agenda $agenda)
    {
        try {
            $agenda->delete();

            return redirect()->route('painel.agenda.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BannersRequest;
use App\Models\Banner;
use Illuminate\Http\Request;

class BannersController extends Controller
{
    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.home.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.home.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.home.banners.edit', compact('banner'));
    }

    public function update(BannersRequest $request, Banner $banner)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $banner->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Banner $banner)
    {
        try {
            $banner->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CaptacaoDePatrociniosTextosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\CaptacaoDePatrociniosTextosRequest;
use App\Models\CaptacaoDePatrocinioTexto;
use Illuminate\Http\Request;

class CaptacaoDePatrociniosTextosController extends Controller
{
    public function index()
    {
        $textos = CaptacaoDePatrocinioTexto::ordenados()->get();

        return view('painel.captacao-de-patrocinios.textos.index', compact('textos'));
    }

    public function create()
    {
        return view('painel.captacao-de-patrocinios.textos.create');
    }

    public function store(CaptacaoDePatrociniosTextosRequest $request)
    {
        try {
            $input = $request->all();

            CaptacaoDePatrocinioTexto::create($input);

            return redirect()->route('painel.captacao-de-patrocinios.textos.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(CaptacaoDePatrocinioTexto $texto)
    {
        return view('painel.captacao-de-patrocinios.textos.edit', compact('texto'));
    }

    public function update(CaptacaoDePatrociniosTextosRequest $request, CaptacaoDePatrocinioTexto $texto)
    {
        try {
            $input = $request->all();

            $texto->update($input);

            return redirect()->route('painel.captacao-de-patrocinios.textos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(CaptacaoDePatrocinioTexto $texto)
    {
        try {
            $texto->delete();

            return redirect()->route('painel.captacao-de-patrocinios.textos.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CaptacaoDePatrociniosTextosImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\CaptacaoDePatrociniosTextosImagensRequest;
use App\Models\CaptacaoDePatrocinioTexto;
use App\Models\CaptacaoDePatrocinioTextoImagem;
use Illuminate\Http\Request;

class CaptacaoDePatrociniosTextosImagensController extends Controller
{
    public function index(CaptacaoDePatrocinioTexto $texto)
    {
        $imagens = CaptacaoDePatrocinioTextoImagem::texto($texto->id)->ordenados()->get();

        return view('painel.captacao-de-patrocinios.textos.imagens.index', compact('texto', 'imagens'));
    }

    public function show(CaptacaoDePatrocinioTexto $texto, CaptacaoDePatrocinioTextoImagem $imagem)
    {
        return $imagem;
    }

    public function store(CaptacaoDePatrociniosTextosImagensRequest $request, CaptacaoDePatrocinioTexto $texto)
    {
        try {
            $input = $request->all();
            $input['imagem'] = CaptacaoDePatrocinioTextoImagem::upload_imagem();
            $input['texto_id'] = $texto->id;

            $imagem = CaptacaoDePatrocinioTextoImagem::create($input);

            $view = view('painel.captacao-de-patrocinios.textos.imagens.imagem', compact('texto', 'imagem'))->render();

            return response()->json(['body' => $view]);
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(CaptacaoDePatrocinioTexto $texto, CaptacaoDePatrocinioTextoImagem $imagen)
    {
        try {
            $imagen->delete();

            return redirect()->route('painel.captacao-de-patrocinios.textos.imagens.index', $texto->id)->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }

    public function clear(CaptacaoDePatrocinioTexto $texto)
    {
        try {
            $texto->imagens()->delete();

            return redirect()->route('painel.captacao-de-patrocinios.textos.imagens.index', $texto->id)->with('success', 'Imagens excluídas com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagens: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CentroDeEstudosTextosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\CentroDeEstudosTextosRequest;
use App\Models\CentroDeEstudoTexto;
use Illuminate\Http\Request;

class CentroDeEstudosTextosController extends Controller
{
    public function index()
    {
        $textos = CentroDeEstudoTexto::ordenados()->get();

        return view('painel.centro-de-estudos.textos.index', compact('textos'));
    }

    public function create()
    {
        return view('painel.centro-de-estudos.textos.create');
    }

    public function store(CentroDeEstudosTextosRequest $request)
    {
        try {
            $input = $request->all();

            CentroDeEstudoTexto::create($input);

            return redirect()->route('painel.centro-de-estudos.textos.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(CentroDeEstudoTexto $texto)
    {
        return view('painel.centro-de-estudos.textos.edit', compact('texto'));
    }

    public function update(CentroDeEstudosTextosRequest $request, CentroDeEstudoTexto $texto)
    {
        try {
            $input = $request->all();

            $texto->update($input);

            return redirect()->route('painel.centro-de-estudos.textos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(CentroDeEstudoTexto $texto)
    {
        try {
            $texto->delete();

            return redirect()->route('painel.centro-de-estudos.textos.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/depoimentos/edit.blade.php
@extends('painel.layout.template')

@section('content')

<legend class="mb-4">
    <h2 class="m-0"><small>DEPOIMENTOS |</small> Editar Depoimento</h2>
</legend>

{!! Form::model($depoimento, [
'route' => ['painel.depoimentos.update', $depoimento->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.depoimentos.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/depoimentos/form.blade.php
@include('painel.layout.flash')

<div class="mb-3 col-12 col-md-12">
    {!! Form::label('nome', 'Nome') !!}
    {!! Form::text('nome', null, ['class' => 'form-control input-text', 'disabled' => 'disabled']) !!}
</div>

<div class="mb-3 col-12 col-md-12">
    {!! Form::label('email', 'E-mail') !!}
    {!! Form::text('email', null, ['class' => 'form-control input-text', 'disabled' => 'disabled']) !!}
</div>

<div class="mb-3 col-12">
    {!! Form::label('mensagem', 'Mensagem') !!}
    {!! Form::textarea('mensagem', null, ['class' => 'form-control input-text', 'readonly']) !!}
</div>

<div class="mb-3 col-12">
    {!! Form::label('espetaculo_id', 'Espetáculo') !!}
    {!! Form::select('espetaculo_id', $espetaculos , old('espetaculo_id'), ['class' => 'form-control select-tipos']) !!}
</div>

<div class="mb-3 col-12">
    <div class="checkbox m-0 @if($depoimento->aprovado == 1) checked @endif">
        <label style="font-weight:bold">
            {!! Form::hidden('aprovado', 0) !!}
            {!! Form::checkbox('aprovado') !!}
            Aprovado
        </label>
    </div>
</div>

<div class="d-flex align-items-center mt-4">
    {!! Form::submit($submitText, ['class' => 'btn btn-success me-1']) !!}

    <a href="{{ route('painel.depoimentos.index') }}" class="btn btn-secondary btn-voltar">Voltar</a>
</div>

laravel/resources/views/painel/depoimentos/index.blade.php
@extends('painel.layout.template')

@section('content')

@include('painel.layout.flash')

<legend class="mb-4">
    <h2 class="m-0">DEPOIMENTOS</h2>
</legend>

@if(!count($depoimentos))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="depoimentos">
        <thead>
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
                <th scope="col">Espetáculo</th>
                <th scope="col">Aprovado</th>
                <th class="no-filter" scope="col"><i class="bi bi-gear-fill me-2"></th>
            </tr>
        </thead>

        <tbody>
            @foreach ($depoimentos as $depoimento)
            <tr class="@if(!$depoimento->lido)alert alert-warning @endif" id="{{ $depoimento->id }}">
                <td data-order="{{ $depoimento->created_at_order }}">{{ $depoimento->created_at }}</td>
                <td>{{ $depoimento->nome }}</td>
                <td class="d-flex flex-row align-items-center">
                    <button class="btn btn-dark btn-sm clipboard me-2" data-clipboard-text="{{ $depoimento->email }}">
                        <i class="bi bi-clipboard"></i>
                    </button>
                    {{ $depoimento->email }}
                </td>
                <td>
                    @if($depoimento->espetaculo_id)
                    {{ $espetaculos->where('id', $depoimento->espetaculo_id)->first()->titulo }}
                    @else
                    Indefinido
                    @endif
                </td>
                <td>
                    @if($depoimento->aprovado == 1)
                    <i class="bi bi-check me-1"></i> Aprovado
                    @else
                    <i class="bi bi-x me-1"></i> Não aprovado
                    @endif
                </td>
                <td class="crud-actions">
                    {!! Form::open([
                    'route' => ['painel.depoimentos.destroy', $depoimento->id],
                    'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm" role="group">
                        <a href="{{ route('painel.depoimentos.show', $depoimento->id ) }}" class="btn btn-success btn-sm">
                            <i class="bi bi-chat-text-fill me-2"></i>Ler Depoimento
                        </a>

                        <a href="{{ route('painel.depoimentos.edit', $depoimento->id ) }}" class="btn btn-primary btn-sm">
                            <i class="bi bi-pencil-fill me-2"></i>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><i class="bi bi-trash-fill me-2"></i>Excluir</button>

                        <a href="{{ route('painel.depoimentos.toggle', $depoimento->id) }}" class="btn btn-sm {{ ($depoimento->lido ? 'btn-warning' : 'btn-success') }}">
                            @if($depoimento->lido)
                            <i class="bi bi-arrow-repeat"></i>
                            @else
                            <i class="bi bi-check2-circle"></i>
                            @endif
                        </a>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

@endif

@endsection

laravel/resources/views/painel/depoimentos/show.blade.php
@extends('painel.layout.template')

@section('content')

<legend class="mb-4">
    <h2 class="m-0">DEPOIMENTOS</h2>
</legend>

<div class="mb-3 col-12">
    <label>Data</label>
    <div class="well">{{ $depoimento->created_at }}</div>
</div>

<div class="mb-3 col-12">
    <label>Nome</label>
    <div class="well">{{ $depoimento->nome }}</div>
</div>

<div class="mb-3 col-12">
    <label>E-mail</label>
    <div class="well">
        <button class="btn btn-dark btn-sm clipboard me-2" data-clipboard-text="{{ $depoimento->email }}">
            <i class="bi bi-clipboard"></i>
        </button>
        {{ $depoimento->email }}
    </div>
</div>

<div class="mb-3 col-12">
    <label>Mensagem</label>
    <div class="well-msg">{!! $depoimento->mensagem !!}</div>
</div>

<div class="mb-3 col-12">
    <label>Aprovado</label>
    @if($depoimento->aprovado == 1)
    <div class="well"><i class="bi bi-check me-1"></i> Aprovado</div>
    @else
    <div class="well"><i class="bi bi-x me-1"></i> Não aprovado</div>
    @endif
</div>

<div class="mb-3 col-12">
    <label>Espetáculo</label>
    @if($espetaculo)
    <div class="well">{{ $espetaculo->titulo }}</div>
    @else
    <div class="well">Indefinido</div>
    @endif
</div>

<div class="d-flex align-items-center mt-4">
    <a href="{{ route('painel.depoimentos.index') }}" class="btn btn-secondary btn-voltar">Voltar</a>
</div>

@stop